# Generated by Django 5.0.7 on 2025-03-21 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinyl',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.order')),
                ('vinyl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vinyl')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vinyls',
            field=models.ManyToManyField(through='pages.OrderItem', to='pages.vinyl'),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='in_transit', max_length=20)),
                ('estimated_delivery', models.DateField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.order')),
            ],
        ),
    ]
